CREATE USER contact IDENTIFIED BY pwd123;
GRANT CONNECT, RESOURCE TO contact;
ALTER USER contact QUOTA UNLIMITED ON USERS;
CREATE USER CONTACT IDENTIFIED BY pwd123;
GRANT CONNECT, RESOURCE TO CONTACT;
ALTER USER CONTACT QUOTA UNLIMITED ON USERS;
exit;